name: Dummy

on:
  workflow_dispatch:

jobs:
  dummy:
    name: Dev and Debug Workflows

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Missing System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.1
          opam-repositories: |
            pin: git+https://github.com/ocaml/opam-repository#c5fc79e7b15c7e1f694867da6248cb0bace7682e
          opam-disable-sandboxing: true

      - run: git rev-parse HEAD
